apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: surfops-create-new-log-entry
  namespace: default
  labels: &labels
    app: surfops
    component: cronjob
spec:
  # At 20:00 on Wednesday.
  schedule: "00 20 * * 3"
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: surfops-create-new-log-entry
            image: andreffs/surfops:latest
            imagePullPolicy: Always
            args:
              - 'python'
              - 'surf.py'
              - 'create-new-log-entry'
              - '--channel'
              - 'general'
            envFrom:
            - secretRef:
                name: surfops-secrets
          restartPolicy: Never