apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: surfops-generate-poll
  namespace: default
  labels: &labels
    app: surfops
    component: cronjob
spec:
  # At 10:30 on Tuesday.
  schedule: "30 10 * * 2"
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: surfops-generate-poll
            image: andreffs/surfops:latest
            imagePullPolicy: Always
            args:
              - 'python'
              - 'surf.py'
              - 'generate-poll'
              - '--channel'
              - 'surfing'
            envFrom:
            - secretRef:
                name: surfops-secrets
          restartPolicy: Never