apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: surfops-update-last-log-entry
  namespace: default
  labels: &labels
    app: surfops
    component: cronjob
spec:
  # At 9:30 on Thursday.
  schedule: "30 9 * * 4"
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: surfops-update-last-log-entry
            image: andreffs/surfops:latest
            imagePullPolicy: Always
            args:
              - 'python'
              - 'surf.py'
              - 'update-last-log-entry'
              - '--channel'
              - 'surfing'
            envFrom:
            - secretRef:
                name: surfops-secrets
          restartPolicy: Never